### PR TITLE
CPD-8052: yaml  data converter fix

### PR DESCRIPTION
**Pull request by ahmad-dev23**
**Motivation**
Upgrade to ruby 3.1.2
Fixes #CPD-8052

**Proposed changes**

**Alternatives considered**

**Testing steps**

### CODE REVIEW

**Review by stephenthedev — APPROVED** [review]

**Comment by marciotoshio** [comment]
Hello 👋

**Comment by pdrakeweb** [comment]
As I understand it, this is functionally the same and necessitated by changes in YAML loading, to it seems reasonable to me.

Also, hello @marciotoshio & @stephenthedev!

**Review by kaushik — APPROVED** [review]

**Comment by kaushik** [comment]
Hello Team @marciotoshio and @pdrakeweb! and thanks for the review XD

**Comment by jamesiarmes** [comment]
Oh, hey, the gangs all here! 👋

**Pull request merged**
